### ISSUE TITLE
Canvas output in Org mode buffer

### ISSUE THREAD

**Issue by theoreticMK** [jaypmorgan/root-mode#3]
Hi, I just discovered this package. As a CERN ROOT user,  I am very happy :)

Is there a way to display a plot/canvas created in an org-mode source code block directly in the buffer? 
If so, could you please add an example to the README? 
If not, is it possible to implement the functionality?

**Comment by jaypmorgan** [comment]
Hi @theoreticMK, there isn't any functionality for that yet -- it was something I was looking to implement in the future (after adding support for the completion engine). Though I don't know if such a thing is inherently possible without a hack work around. For example, a work around I foresee is saving the figure to a temporary file at the time of plotting, and the org-mode block returning the name of the temporary file such as:

```
#+begin_src :results value file
<<plot and save>>
<<return filename>>
#+end_src
``` 
This will be something I need to test for!

I'll leave this issue open as a reference in-case I, or anyone else makes this process a little smoother.

**Comment by jaypmorgan** [comment]
Further to my explanation, I've taken an example from the root documentation to get a working example for you. 

In this example, I am creating a function that creates a polar plot. This function returns the path to the file that was saved. Finally, I am printing the name of the file with `printf`. This last part is necessary otherwise there will be other things in the output such as the `(const char*)` type that gets prepended to the repl output.

```
#+begin_src cern-root :results output file
const char* macro3(){
    const char* filename{"/tmp/polar-plot.png"};
    auto c = new TCanvas("myCanvas","myCanvas",600,600);
    double rmin = 0.;
    double rmax = TMath::Pi()*6.;
    const int npoints = 1000;
    double r[npoints];
    double theta[npoints];
    for (int ipt = 0; ipt < npoints; ipt++) {
        theta[ipt] = ipt*(rmax-rmin)/npoints+rmin;
        r[ipt] = TMath::Sin(theta[ipt]);
    }
    auto grP1 = new TGraphPolar(npoints,theta,r);
    grP1->SetTitle("A Fan");
    grP1->SetLineWidth(3);
    grP1->SetLineColor(2);
    grP1->Draw("L");
    gPad->Update();
    grP1->GetPolargram()->SetToRadian();
    c->SaveAs(filename);
    return filename;
}

const char* filename = macro3();
printf("%s", filename);
#+end_src
```

When I execute this source code block, the image is shown directly in the document. I've added this explanation here: https://jaypmorgan.github.io/cern-root-mode/#orga0cc415

Please reopen if you have some comments on how to make it better :-)

**Comment by theoreticMK** [comment]
Great, thanks for the example :+1:
